const { DatabaseSync } = require('node:sqlite');
const bcrypt = require('bcryptjs');
const path = require('path');
const dbPath = path.join(__dirname, 'data', 'neurallgo.db');
const db = new DatabaseSync(dbPath);
const pass = process.argv[2] || '12345';
const hash = bcrypt.hashSync(pass, 12);
const info = db.prepare("UPDATE users SET password_hash=? WHERE email='admin@localhost'").run(hash);
console.log('Filas afectadas:', info.changes);
console.log('Nueva contraseña del Panel Empresarial (admin@localhost):', pass);
